/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MetadataEncodingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decodeMetadata"
      | "getWearables"
      | "hexStringToUint"
      | "uintToHexString"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decodeMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWearables",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hexStringToUint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "uintToHexString",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "decodeMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWearables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hexStringToUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uintToHexString",
    data: BytesLike
  ): Result;
}

export interface MetadataEncoding extends BaseContract {
  connect(runner?: ContractRunner | null): MetadataEncoding;
  waitForDeployment(): Promise<this>;

  interface: MetadataEncodingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decodeMetadata: TypedContractMethod<
    [metadata: BigNumberish],
    [
      [bigint[], boolean, bigint, bigint, string] & {
        wearableIds: bigint[];
        isTalkative: boolean;
        speed: bigint;
        laziness: bigint;
        color: string;
      }
    ],
    "view"
  >;

  getWearables: TypedContractMethod<
    [metadata: BigNumberish],
    [bigint[]],
    "view"
  >;

  hexStringToUint: TypedContractMethod<[hexString: string], [bigint], "view">;

  uintToHexString: TypedContractMethod<[value: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decodeMetadata"
  ): TypedContractMethod<
    [metadata: BigNumberish],
    [
      [bigint[], boolean, bigint, bigint, string] & {
        wearableIds: bigint[];
        isTalkative: boolean;
        speed: bigint;
        laziness: bigint;
        color: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWearables"
  ): TypedContractMethod<[metadata: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hexStringToUint"
  ): TypedContractMethod<[hexString: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "uintToHexString"
  ): TypedContractMethod<[value: BigNumberish], [string], "view">;

  filters: {};
}
