packages:
  - name: skybuds
    environment: {}
    parameters: {}
    actions:
      - name: get_nfts
        runtime: 'go:default'
        environment:
          ALCHEMY_KEY: "${ALCHEMY_KEY}"
      - name: get_owner
        runtime: 'go:default'
        environment:
          ALCHEMY_KEY: "${ALCHEMY_KEY}"